ZIPFILE="portablizer-mac.zip"

all: clean build package printmd5sum

clean:
	@echo "Running clean up..."
	rm -rf dist build

build:
	@echo "Building..."
	pyinstaller -y spec.mac.spec

package:
	@echo "Making archive..." && cd dist && \
	(echo -e "Portablizer for Mac\n" \
	| zip $(ZIPFILE) -r Portablizer.app -z)

printmd5sum:
	@echo "Completed! Here's the MD5SUM of $(ZIPFILE):" && \
	md5 -q dist/$(ZIPFILE)
	@open dist &

.PHONY: all clean package build printmd5sum
